### ISSUE TITLE
Need explanations and tests for broadcast_index function

### ISSUE THREAD

**Issue by gizyh** [minitorch/Module-2#21]
> Convert a `big_index` into `big_shape` to a smaller `out_index` into `shape` following broadcasting rules.

I don't understand why a big index need to be converted to a smaller index, isn't the broadcasting rules about "augmenting" the shape of a tensor? 

 I tried to look up the test cases for the broadcast_index function and have nothing found. Maybe more test cases need to be added for better understanding and test coverage.

**Comment by srush** [comment]
Sorry. You are right that the language here is pretty confusing. I will add a test and clarify more. 

What this means is the following. 

Imagine you have two tensors , one of `big_shape` (10, 2) and the other of `shape`  (1, 2). Then you are given a `big_index` (4, 1). What is the `out_index` it corresponds to in the second tensor? Well that is `(0, 1)`. (since it couldn't be (4, 1) ). 

That is what this function should do.

**Comment by gizyh** [comment]
Got it, thanks!

**Comment by gizyh** [comment]
Got it, thanks!

**Comment by gizyh** [comment]
Got it, thanks!
